services:
  web:
    build: .
    command: bash -lc "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/support_tickets_api_development
      RAILS_ENV: development
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: support_tickets_api_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d support_tickets_api_development"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  bundle_data: